# Generated by Django 3.0.5 on 2020-04-16 09:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Messageapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagecategory',
            name='pdfUpload',
            field=models.FileField(default=django.utils.timezone.now, upload_to='uploads/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
